---
abstract: 'Fast thread queues'
author:
  - 'Leon Timmermans <fawaka@gmail.com>'
build_requires:
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.4004
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.4004
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Thread-Channel
requires:
  Sereal: 0
  XSLoader: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Thread-Channel
  repository: git://github.com/Leont/thread-channel.git
version: 0.001
